language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests & document coverage
addons:
  apt:
    packages:
      - python-coverage
script:
  - pytest
  - pytest --cov=AutoTransformPy tests/

# code coverage badge
after_success:
  - codecov
