language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/UBC-MDS/AutoTransformPy

# command to run tests
script: pytest
